FROM node:alpine

WORKDIR /app

COPY ./package.json ./
COPY ./tsconfig.json ./

RUN npm install
RUN npm install -g typescript
RUN npm install -g ts-node


COPY ./ ./

RUN chmod 777 node_modules
CMD ["npm", "run", "dev"]
