FROM node:alpine

WORKDIR /usr/app

COPY --chown=node:node ./package.json ./
COPY tsconfig.json ./

RUN npm install
RUN npm install -g typescript
RUN npm install -g ts-node
RUN ls -a

COPY --chown=node:node ./ ./

CMD ["npm", "run", "dev"]

